### ISSUE TITLE
Error while using the $submissions = $odk->projects($projectId)->forms($xmlFormId)->submissions()->get();

### ISSUE THREAD

**Issue by rbhalla81** [mchev/laravel-odk#1]
**ErrorException**
htmlspecialchars() expects parameter 1 to be string, object given (View: D:\xampp\htdocs\laravel\resources\views\pages\dashboard.blade.php)

I'm trying to display or view submissions data on the screen.

**Comment by mchev** [comment]
Try to dd() your query in the controller.
```

$submissions = $odk->projects($projectId)->forms($xmlFormId)->submissions()->get();
dd($submissions);
```

**Comment by rbhalla81** [comment]
Tried the suggested solution. 

```
$projectId ="1";
$xmlFormId="HouseholdSurvey1";

$submissions = $odk->projects($projectId)->forms($xmlFormId)->submissions()->get();
dd($submissions);
```

But, got the below error:

```
{#1467 ▼
  +"message": "Invalid input data type: expected 'projects' to be (integer)"
  +"code": 400.11
  +"details": {#1462 ▼
    +"value": "projects"
    +"expected": "integer"
  }
}
```

**Comment by mchev** [comment]
The message is clear : Invalid input data type: expected 'projects' to be (integer)

`$projectId ="1";` should be `$projectId =1;`

**Comment by rbhalla81** [comment]
Tried the same but had no success. 

```
{#1467 ▼
  +"message": "Could not find the resource you were looking for."
  +"code": 404.1
}
```

Further, can you suggest how to view the submissions of form in a table and also have an edit link of enketo?

**Comment by mchev** [comment]
- Are you sure with your xmlFormId?
- Is your form published in odk central?
- Your credentials used in .env file can have access to this form? 

I just tried the same request with success.

**Comment by rbhalla81** [comment]
Yes, I have checked the project and form ids in Central.

**Comment by mchev** [comment]
The error is returned by ODK Central, so for me the request work but ODK can't find the form you are looking for.
Without more informations i can't help. But i would try to go gradually. 
First `dd($odk->projects($projectId)->get());`
Then `dd($odk->projects($projectId)->forms($xmlFormId)->get());`
etc.
And see what happen.

**Comment by rbhalla81** [comment]
The APIs work fine to retrieve all data. But, while trying to pass the condition like project id or form id, it doesn't work.

Tried the following:
`$projects = OdkCentral::projects(1)->get();`

Error:
```
ErrorException
htmlspecialchars() expects parameter 1 to be string
```

D:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Support\helpers.php:118

```
 *

     * @param  \Illuminate\Contracts\Support\DeferringDisplayableValue|\Illuminate\Contracts\Support\Htmlable|string|null  $value

     * @param  bool  $doubleEncode

     * @return string

     */

    function e($value, $doubleEncode = true)

    {

        if ($value instanceof DeferringDisplayableValue) {

            $value = $value->resolveDisplayableValue();

        }

 

        if ($value instanceof Htmlable) {

            return $value->toHtml();

        }

 

        **return htmlspecialchars($value ?? '', ENT_QUOTES, 'UTF-8', $doubleEncode);**

    }

}

 

if (! function_exists('env')) {

    /**

     * Gets the value of an environment variable.

     *

     * @param  string  $key

     * @param  mixed  $default

     * @return mixed

     */

    function env($key, $default = null)

    {

        return Env::get($key, $default);

    }


```

**Comment by mchev** [comment]
According to this error it seems that there is a problem in your .env or config/odkcentral.php

Did you publish the config?
Also, i realize that I didn't specify in the documentation that you have to put quotation marks around each value :

```
ODK_API_URL="https://your_host.com/v1"
ODK_USER_EMAIL="your_email"
ODK_USER_PASSWORD="your_password"
```

**Comment by rbhalla81** [comment]
I checked both the files. Seems fine. However, I'm able to get the all data using the APIs but when trying to define a variable and then call it in `$projects = OdkCentral::projects($projectId)->get();` (or) `$projects = OdkCentral::projects(1)->get(); `doesn't work.

But, `$projects = OdkCentral::projects()->get();` this works fine.

**Comment by mchev** [comment]
> However, I'm able to get the all data using the APIs but when trying to define a variable and then call it in $projects = OdkCentral::projects($projectId)->get(); (or) $projects = OdkCentral::projects(1)->get(); doesn't work.

Could you copy here the response/error? It "doesn't work" cannot help me to understand or help you.

**Comment by rbhalla81** [comment]
> The APIs work fine to retrieve all data. But, while trying to pass the condition like project id or form id, it doesn't work.
> 
> Tried the following:
> `$projects = OdkCentral::projects(1)->get();`
> 
> Error:
> 
> ```
> ErrorException
> htmlspecialchars() expects parameter 1 to be string
> ```
> 
> D:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Support\helpers.php:118
> 
> ```
>  *
> 
>      * @param  \Illuminate\Contracts\Support\DeferringDisplayableValue|\Illuminate\Contracts\Support\Htmlable|string|null  $value
> 
>      * @param  bool  $doubleEncode
> 
>      * @return string
> 
>      */
> 
>     function e($value, $doubleEncode = true)
> 
>     {
> 
>         if ($value instanceof DeferringDisplayableValue) {
> 
>             $value = $value->resolveDisplayableValue();
> 
>         }
> 
>  
> 
>         if ($value instanceof Htmlable) {
> 
>             return $value->toHtml();
> 
>         }
> 
>  
> 
>         **return htmlspecialchars($value ?? '', ENT_QUOTES, 'UTF-8', $doubleEncode);**
> 
>     }
> 
> }
> 
>  
> 
> if (! function_exists('env')) {
> 
>     /**
> 
>      * Gets the value of an environment variable.
> 
>      *
> 
>      * @param  string  $key
> 
>      * @param  mixed  $default
> 
>      * @return mixed
> 
>      */
> 
>     function env($key, $default = null)
> 
>     {
> 
>         return Env::get($key, $default);
> 
>     }
> ```

Please refer this comment. Getting same error.

**Comment by mchev** [comment]
Are you trying to display the project in blade?  Have you tried to `dd(OdkCentral::projects($projectId)->get());` ?
What the die and dump says?

**Comment by rbhalla81** [comment]
Yes, I'm using blade to display the ODK response. It works while using `dd(OdkCentral::projects($projectId)->get());` but unable to display in view.

In addition, how can we edit a submission and update?

**Comment by mchev** [comment]
I'm sorry but this is not an issue with the package. For help with laravel and blade you should try stackoverflow. For example first google result : https://stackoverflow.com/questions/43217872/laravel-htmlspecialchars-expects-parameter-1-to-be-string-object-given
