### ISSUE TITLE
Fields schema

### ISSUE THREAD

**Issue by hamzaEssaadi** [mchev/laravel-odk#12]
I tired to get fields definitions like this : 
`$form = $odk->projects($projectId)->forms($xmlFormId)->fields()->get();`
but its gives this error : 'Too few arguments to function Illuminate\Support\Collection::get(), 0 passed in'

**Comment by nekovly** [comment]
To get the form fields you should use this one:
```php
$form = $odk->projects($projectId)->forms($xmlFormId)->fields();
```
