### ISSUE TITLE
Error exception while using OdkCentral::projects

### ISSUE THREAD

**Issue by rbhalla81** [mchev/laravel-odk#2]
While trying "$submissions = OdkCentral::projects($projectId)->forms($xmlFormId)->submissions()->get();"

Receiving the below error message:

ErrorException
Non-static method Mchev\LaravelOdk\OdkCentral::projects() should not be called statically (View: D:\xampp\htdocs\laravel\resources\views\pages\dashboard.blade.php)

However, `$projects = $odk->projects()->get();` this works fine.

**Comment by mchev** [comment]
If you use the Facade :

`use OdkCentral;`

then call : 

`$project = OdkCentral::projects($projectId)->get();`

**Comment by rbhalla81** [comment]
Thanks for your prompt response. 

Tried the suggested facade but receiving the following error exception:

_```
ErrorException
The use statement with non-compound name 'OdkCentral' has no effect
```_

**Comment by mchev** [comment]
```
<?php

namespace App\Http\Controllers;

use OdkCentral; // Instead of Mchev\LaravelOdk\OdkCentral:

class SomeController extends Controller
{
    public function testOdk()
    {

        $project = OdkCentral::projects(1)->get();

        $form = OdkCentral::projects(1)->forms('basic')->get();

        dd($project, $form);

    }
}

```

**Comment by rbhalla81** [comment]
Working fine now.

I have just added the following as suggested:

```
namespace App\Http\Controllers;

use OdkCentral;
```

Thanks for your help and support. :)
