### ISSUE TITLE
Error in Update Answers

### ISSUE THREAD

**Issue by rbhalla81** [mchev/laravel-odk#4]
Trying to update the answers using the following

```
$answers = OdkCentral::projects($projectId)->forms($xmlFormId)->submissions($submissionId)->answers()->update([
  'HeadOfHouseholdName' => 'Test Update'  // this is as per my demo ODK form
]);
```
But, this work like a charm for the status
```
// Updating Submission metadata
$submissions = OdkCentral::projects($projectId)->forms($xmlFormId)->submissions($instanceId)->update([
  'reviewState' => 'approved' // null, edited, hasIssues, rejected, approved | enum
]);
```

**Comment by rbhalla81** [comment]
@mchev I have tried to do the XML update. But couldn't succeed. Any idea or roadmap to include the feature in this component? This update feature shall be the utmost required. Please help.

**Comment by mchev** [comment]
https://docs.getodk.org/central-submissions/#submission-editing
